language: rust
rust: nightly
sudo: false

cache: cargo

notifications:
  email:
    on_failure: always

matrix:
  fast_finish: true
  include:
    # Targets
    - name: "linux"
      os: linux
      env: RUST_BACKTRACE=full
    - name: "osx"
      os: osx
      osx_image: xcode11.3
      env: RUST_BACKTRACE=full
    - name: "windows"
      os: windows

    # Tools:
    - name: "rustfmt"
      script: |
        if rustup component add rustfmt-preview; then
            cargo fmt --all -- --check
        fi
    - name: "clippy"
      script: |
        if rustup component add clippy-preview rustc-dev; then
            cargo clippy --all
        fi
    - name: "Shellcheck"
      script:
        - shellcheck --version
        - shellcheck ci/*.sh

script: sh ci/run.sh
