[package]
name = "semverver"
description = "Automatic verification of SemVer adherence in Rust library crates"
repository = "https://github.com/rust-dev-tools/rust-semverver"
readme = "README.md"
keywords = ["semver", "plugin"]
categories = ["development-tools", "development-tools::cargo-plugins"]
version = "0.1.46"
authors = ["Inokentiy Babushkin <twk@twki.de>"]
license-file = "LICENSE"
edition = "2018"

[dependencies]
cargo = "0.48"
crates-io = "0.32"
curl = "0.4.21"
env_logger = "0.7"
anyhow = "1.0.27"
log = "0.4"
rand = "0.7"
semver = "0.9"
serde = { version = "1.0.84", features = ["derive"] }
serde_json = "1.0.34"

[dev-dependencies]
quickcheck = "0.9"
